---

- hosts: all
  become: true
  tasks:

  - name: update the repository index for Debian-like OS
    apt:
      update-cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install lastest version of apache2 package
    apt:
      name: apache2
      state: latest
    when: when: ansible_distribution == "Ubuntu"

  - name: install latest verison of php module for apache
    apt:
      name: libapache2-mod-php
      state: latest
    when: when: ansible_distribution == "Ubuntu"
