---

- hosts: all
  become: true
  tasks:

  - name: update the respository DB and install lastest version of apache2 and php packages on Debian
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
      update-cache: yes
    when: ansible_distribution == "Debian"

- name: update the respository DB and install lastest version of apache2 and php packages on CentOS
    apt:
      name: 
        - httpd
        - php
      state: latest
      update-cache: yes
    when: ansible_distribution == "CentOS"
