---

- hosts: all
  become: true
  tasks:

  - name: update the respository DB and install lastest version of apache2 and php packages
    apt:
      name: 
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: latest
      update-cache: yes
